colors = ['darkred', 'darkmagenta', 'darkolivegreen',
 'darkorange',
 'darkorchid',
 'darkseagreen',
  'darksalmon',
  'darkslateblue',
  'crimson', 'antiquewhite',
  'aqua', 'aquamarine', 'azure',
  'beige', 'bisque', 'blanchedalmond',
  'blue','blueviolet', 'brown',
  'burlywood', 'cadetblue', 'chartreuse',
  'chocolate', 'coral']
