World = {
'China': 'China',
'India': 'India',
'Russia': 'Russia',
'US': 'United_States_of_America',
'UK': 'United_Kingdom',
'BR':'Brazil',
'CA':'Canada',
'FR': 'France',
'DE': 'Germany',
'HK': 'Hong_Kong',
'IR': 'Iran',
'IT': 'Italy',
'JP': 'Japan',
'MX': 'Mexico',
'NI': 'Nigeria',
'NO': 'Norway',
'ID': 'Indonesia',
'SI': 'Singapore',
'ES': 'Spain',
'PK': 'Pakistan',
'PH': 'Philippines',
'SG': 'Senegal',
'SW': 'Sweden',
'TU': 'Turkey',
'TH': 'Thailand',
'VT': 'Vietnam',
'SA': 'South_Africa'
}
